title: "Salinity SOP"
logo: images/logo-ocean-gliders.png
execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/OceanGlidersCommunity/Salinity_SOP
  branch: main
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  comments:
    utterances:
      repo: "OceanGlidersCommunity/Salinity_SOP"
bibtex_bibfiles:
    - salinity.bib
sphinx:
  config:
    bibtex_reference_style: author_year
